# Copyright (c) 2025 Daniel Rossinsky (https://github.com/rtsworks)
# SPDX-License-Identifier: MIT

# This Makefile implements the lint → test → build workflow, integrates
# CPPCheck (MISRA), Ceedling, and gcovr, and supports debug/release builds

# --------------------------------- GENERAL ---------------------------------- #
# The target binary to be created.
TARGET := prog.bin
# Build selection variable (debug by default).
BUILD := debug

# ----------------------------- Directory paths ------------------------------ #
# Source file directory.
SRC_DIR := ./src
# Include file directory.
INCLUDE_DIR := ./include
# Script file directory.
SCRIPT_DIR := ./script
# Build directory root.
BUILD_ROOT = ./build
# Contains all the build artifacts.
BUILD_DIR := $(BUILD_ROOT)/$(BUILD)
# Contains CPPCheck related artifacts.
CPPCHECK_DIR := $(BUILD_ROOT)/cppcheck
# Bin directory root.
BIN_ROOT = ./bin
# Contains the output files.
BIN_DIR := $(BIN_ROOT)/$(BUILD)

# ---------------------------------- Files ----------------------------------- #
# Source files discovered recursively under SRC_DIR.
SRCS := $(shell find $(SRC_DIR) -type f -name '*.c')
# Object files mirror the source directory structure inside BUILD_DIR.
OBJS := $(SRCS:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)
# Dependency (.d) files are auto-generated by gcc (-MMD -MP) to track header 
# changes.
DEPS := $(OBJS:.o=.d)

# ----------------------------- Compiler config ------------------------------ #
# Select the C compiler.
CC := gcc
# Release build compiler flags.
CFLAGS.release := -Os
# Debug build compiler flags.
CFLAGS.debug := -O0 -ggdb3
# Common compiler flags: strict warnings, pedantic mode, stack usage reports,
# and section-splitting to allow the linker to garbage-collect unused code.
CFLAGS := $(CFLAGS.$(BUILD)) -std=c99 -pedantic -Wall -Wextra -Werror        \
							 -Winline -Wconversion -Wpadded -Wshadow -Wundef \
							 -Wdouble-promotion -fno-common -fstack-usage    \
							 -ffunction-sections -fdata-sections -pthread
# Release build preprocessor flags.
CPPFLAGS.release := -DNDEBUG
# Debug build preprocessor flags.
CPPFLAGS.debug :=
# Common preprocessor flags: enable _GNU_SOURCE, add include paths, and instruct
# GCC to auto-generate dependency files (.d) during compilation.
CPPFLAGS := -D_GNU_SOURCE $(CPPFLAGS.$(BUILD)) -I$(SRC_DIR) -I$(INCLUDE_DIR) \
            -MMD -MP
# Release build linker flags.
LDFLAGS.release := -s
# Debug build linker flags.
LDFLAGS.debug :=
# Library paths.
LIBPATHS :=
# Common linker flags: include build-specific flags, optional library paths, 
# linker map output, and enable garbage collection of unused functions/data.
LDFLAGS := $(LDFLAGS.$(BUILD)) $(LIBPATHS) -Wl,-Map=$(BIN_DIR)/$(TARGET).map \
           -Wl,--gc-sections #-Wl,--print-gc-sections
# Link libraries
LDLIBS := -lm -pthread

# ------------------------------ CPPCheck config ----------------------------- #

# Number of threads to be used by CPPCheck.
CPPCHECK_THREADS := 1

# Flags to be used by the CPPCheck tool.
CPPCHECK_FLAGS := --verbose
CPPCHECK_FLAGS += --error-exitcode=1
CPPCHECK_FLAGS += --suppress=missingIncludeSystem
CPPCHECK_FLAGS += --suppress=unmatchedSuppression
CPPCHECK_FLAGS += --suppress=misra-c2012-21.6
CPPCHECK_FLAGS += --inline-suppr
CPPCHECK_FLAGS += -I$(INCLUDE_DIR)
CPPCHECK_FLAGS += --cppcheck-build-dir=$(CPPCHECK_DIR)
CPPCHECK_FLAGS += --relative-paths=.
CPPCHECK_FLAGS += --platform=$(SCRIPT_DIR)/type_sizes.xml
CPPCHECK_FLAGS += --language=c
CPPCHECK_FLAGS += --std=c99
CPPCHECK_FLAGS += --library=posix.cfg
CPPCHECK_FLAGS += --enable=all
CPPCHECK_FLAGS += --safety
CPPCHECK_FLAGS += --check-level=exhaustive
CPPCHECK_FLAGS += --report-type=misra-c-2012
CPPCHECK_FLAGS += --inconclusive
CPPCHECK_FLAGS += --addon=$(SCRIPT_DIR)/misra.json
CPPCHECK_FLAGS += --addon=$(SCRIPT_DIR)/threadsafety.json
CPPCHECK_FLAGS += -j$(CPPCHECK_THREADS)

# ------------------------------- Ceedling path ------------------------------ #

# Path to the local ceedling folder.
CEEDLING := vendor/ceedling/bin/ceedling

# ------------------------------- Make targets ------------------------------- #

# Ensure workflow targets are not confused with files.
.PHONY: all lint test build clean

# Make lint → test → build workflow. Stop the workflow when any step fails.
# Default make target: Run the build prerequisite.
all: build
# Build target runs the test prerequisite.
build: test
# Test target runs lint prerequisite.
test: lint

# Run static analysis with CPPCheck using the configured MISRA and thread-safety
# addons.
lint: | $(CPPCHECK_DIR)
	cppcheck $(CPPCHECK_FLAGS) $(SRC_DIR)

# Run Ceedling tests + gcovr coverage tool.
test:
	ruby $(CEEDLING) gcov:all

# Build the project binary.
build: $(BIN_DIR)/$(TARGET)

# Link the object files into an executable.
$(BIN_DIR)/$(TARGET): $(OBJS) | $(BIN_DIR)
	$(CC) $(LDFLAGS) $(OBJS) $(LDLIBS) -o $@

# Compile all the sources into object files.
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	mkdir -p $(dir $@)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

# Create the directories below when asked.
$(BIN_DIR) $(BUILD_DIR) $(CPPCHECK_DIR):
	mkdir -p $@

# Clean up the project. 'clobber' removes Ceedling build artifacts and
# auto-generated mocks. Then remove our own build/ and bin/ directories.
clean:
	ruby $(CEEDLING) clobber
	rm -rf $(BUILD_ROOT)
	rm -rf $(BIN_ROOT)

# Include .d files to ensure make detects changes in .h files.
-include $(DEPS)
